POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "name":"tatang",
    "email":"nthia4@gmail.com",
    "password":"tatang123",
    "password_confirmation":"tatang123"
}


###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"nthia4@gmail.com",
    "password":"tatang123"
}


###
GET http://localhost:3000/api/v1/auth/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImlhdCI6MTcwMDM3OTc2Mn0._uNSJTrIf3AQAiSBjvjPy154cYuQCg1A1ntpSexGHxY
